import random from 'random-n';

export const lg1 = ['apron', 'captive', 'drover', 'many', 'snore', 'bandit', 'catch', 'event', 'marble', 'stamp', 'basket', 'cheeky', 'fade', 'monster', 'steel', 'bench', 'chess', 'fate', 'mood', 'team', 'billy', 'cloak', 'field', 'navy', 'term', 'black', 'clue', 'final', 'netball', 'torch', 'block', 'contest', 'fleet', 'pilot', 'tower', 'bloom', 'crew', 'groom', 'plenty', 'ugly', 'blue', 'crown', 'head', 'seal', 'vast', 'break', 'desk', 'infant', 'shake', 'zone', 'brick', 'display', 'jumper', 'shine', 'zoom', 'bunker', 'doctor', 'label', 'skill', 'cabin', 'drive', 'lemon', 'sleep'];

export const lsc1 = ['actor', 'dodo', 'army', 'Fiji', 'data', 'banjo', 'Dreaming', 'bank', 'forest', 'flask', 'cartoon', 'era', 'bill', 'France', 'invent', 'chant', 'flint', 'buy', 'inlet', 'laptop', 'chapter', 'fort', 'freedom', 'Japan', 'password', 'dance', 'Inca', 'Mabo', 'lake', 'power', 'Gibbs', 'nomad', 'price', 'rain', 'proof', 'harp', 'Odin', 'trust', 'sandbank', 'scale', 'paint', 'Petra', 'vote', 'silt', 'space', 'plot', 'saint', 'wage', 'wild', 'volt', 'poem', 'sharp', 'solo', 'strum', 'talent', 'yarn'];

export const lg2 = ['aboard', 'could', 'jeans', 'pattern', 'skipper', 'advise', 'couple', 'joey', 'peanut', 'slather', 'afraid', 'cricket', 'jumbuck', 'people', 'sleeve', 'alien', 'cruise', 'kingdom', 'perhaps', 'smuggle', 'alter', 'crunch', 'kneel', 'picket', 'sneeze', 'angel', 'curse', 'lapel', 'preacher', 'sponge', 'anteater', 'custard', 'leapfrog', 'prize', 'stadium', 'apple', 'deduce', 'leather', 'promise', 'station', 'arrow', 'delete', 'leech', 'prow', 'strange', 'attack', 'denim', 'lentil', 'puzzled', 'suggest', 'awful', 'detain', 'limestone', 'python', 'sultan', 'balm', 'discard', 'loan', 'quiver', 'survey', 'bamboo', 'disdain', 'maggot', 'quota', 'tantrum', 'barge', 'dollop', 'marine', 'rabbit', 'tartan', 'beckon', 'domain', 'methane', 'rayon', 'teeter', 'billycart', 'either', 'mirror', 'relief', 'tether', 'blanket', 'empire', 'missile', 'replay', 'thermos', 'bleat', 'engross', 'model', 'respect', 'thimble', 'bloated', 'esteem', 'mourn', 'retired', 'tiara', 'brake', 'exclaim', 'mutiny', 'ritual', 'tomato', 'brolga', 'explore', 'nervous', 'rudder', 'torpedo', 'calm', 'ferret', 'nickname', 'scandal', 'torso', 'caption', 'frantic', 'night', 'scared', 'trinket', 'chapel', 'futon', 'nylon', 'scent', 'trivia', 'cheep', 'garbage', 'often', 'search', 'turnstile', 'chief', 'garment', 'ooze', 'serious', 'urgent', 'clothe', 'goggles', 'opal', 'several', 'vessel', 'combat', 'hazard', 'parry', 'shearer', 'village', 'compete', 'injure', 'passive', 'shield', 'wardrobe', 'contort', 'instead', 'pasture', 'shilling', 'waterproof', 'cotton', 'jaunty', 'patrol', 'sight', 'wetsuit', 'windmill'];

export const lsc2 = ['accent', 'ark', 'accuse', 'atlas', 'acid', 'album', 'Aztecs', 'archive', 'Britain', 'Aldrin', 'alto', 'Crete', 'asset', 'Burke', 'angle', 'anthem', 'cubit', 'border', 'canyon', 'area', 'author', 'Delphi', 'convict', 'cavern', 'atom', 'clef', 'druid', 'court', 'China', 'balance', 'diva', 'giant', 'debate', 'climate', 'bisect', 'flute', 'lance', 'duty', 'desert', 'broadband', 'fresco', 'legend', 'earn', 'Flinders', 'computer', 'jazz', 'moat', 'elect', 'Greece', 'digit', 'lento', 'myth', 'envoy', 'India', 'internet', 'lute', 'Neptune', 'judge', 'island', 'intersect', 'movie', 'scroll', 'Menzies', 'jungle', 'ion', 'Mozart', 'Sparta', 'nation', 'Kenya', 'mouse', 'novel', 'toga', 'pardon', 'lagoon', 'Newton', 'opera', 'Zeus', 'patron', 'Murray', 'orbit', 'organ', 'police', 'range', 'predict', 'pencil', 'protect', 'valley', 'propel', 'pitch', 'plaster', 'prompt', 'script', 'sound', 'tango', 'tenor', 'theme', 'trumpet', 'usher'];

export const lg3 = ['affluent', 'bystander', 'devout', 'piecemeal', 'restraint', 'aghast', 'cabana', 'diligent', 'pierce', 'rigmarole', 'agile', 'calamari', 'dissimilar', 'pilgrim', 'robbery', 'alibi', 'calcium', 'disturbance', 'pinafore', 'ruminate', 'allotment', 'calendar', 'dubious', 'pineapple', 'sachet', 'amiable', 'callus', 'dumbbell', 'pitiful', 'salmon', 'animated', 'canopy', 'duplicity', 'plantation', 'salvage', 'arena', 'carriage', 'dutiful', 'plaque', 'sauna', 'aromatic', 'cashmere', 'eclectic', 'platelet', 'scour', 'artesian', 'cavalcade', 'emporium', 'plausible', 'scrupulous', 'ascend', 'ceiling', 'extinguish', 'plummet', 'sentimental', 'astonish', 'chaos', 'extremity', 'polenta', 'sequin', 'astrology', 'chaplain', 'fabulous', 'pollinate', 'shepherd', 'attendance', 'chemist', 'feisty', 'porridge', 'surveyor', 'attitude', 'chortle', 'flamboyant', 'potoroo', 'turmoil', 'auburn', 'cocoon', 'hindrance', 'practise', 'typewriter', 'auction', 'coleslaw', 'impasse', 'precision', 'umbrella', 'autumn', 'collarbone', 'impetuous', 'presentable', 'uncanny', 'aversion', 'collision', 'incisor', 'pretzel', 'universal', 'awkward', 'commandment', 'interfere', 'prospector', 'unruly', 'badger', 'communal', 'interim', 'proviso', 'unscathed', 'badminton', 'compelling', 'karate', 'punctual', 'urgency', 'baggage', 'complaint', 'khaki', 'pungent', 'utensil', 'barricade', 'compote', 'loathsome', 'purchase', 'vacation', 'bedraggled', 'compromise', 'locomotive', 'pursuit', 'vaporous', 'bedridden', 'conceal', 'maritime', 'putrid', 'variable', 'begrudge', 'concourse', 'maverick', 'quadruped', 'vendetta', 'bettong', 'confession', 'meerkat', 'quarrel', 'versus', 'bewilder', 'confidence', 'membrane', 'quay', 'vertigo', 'bikini', 'conniving', 'migraine', 'queasy', 'veteran', 'billabong', 'contaminate', 'mollify', 'ramshackle', 'voyage', 'biscuit', 'contour', 'morale', 'rational', 'wallaby', 'bookkeeper', 'contraband', 'niece', 'recycle', 'wastage', 'boundary', 'cornice', 'nonplussed', 'redundant', 'watertight', 'bovine', 'corridor', 'obstinate', 'regale', 'weasel', 'braille', 'cougar', 'pageant', 'reindeer', 'widespread', 'bravado', 'deign', 'paradox', 'relevant', 'withhold', 'briefcase', 'detergent', 'paramount', 'renovate', 'woeful', 'brochure', 'deuce', 'paunch', 'reprieve', 'wreath', 'bushranger', 'devious', 'pewter', 'residual', 'yearling', 'zealot'];

export const lsc3 = ['abstract', 'abacus', 'abolish', 'Amsterdam', 'antivirus', 'acclaim', 'alms', 'activist', 'bight', 'astronaut', 'bassoon', 'antique', 'agenda', 'blizzard', 'avatar', 'bestseller', 'Ares', 'asylum', 'drought', 'circuit', 'canvas', 'Atlantis', 'ballot', 'epicentre', 'Curie', 'chisel', 'atrium', 'charity', 'Europe', 'digital', 'chord', 'chariot', 'consumer', 'Everest', 'dilution', 'chorus', 'Corinth', 'courtesy', 'Gobi', 'Einstein', 'cinema', 'cutlass', 'custodian', 'habitat', 'futuristic', 'circus', 'dinosaur', 'embargo', 'Hungary', 'gene', 'claves', 'embalm', 'faculty', 'Israel', 'genome', 'concert', 'emperor', 'forum', 'Korea', 'gigabyte', 'duet', 'extinct', 'impeach', 'loch', 'hologram', 'festival', 'florin', 'lawyer', 'Manila', 'hyperspace', 'genre', 'Hittites', 'mayor', 'Mexico', 'integer', 'historian', 'knight', 'ministry', 'Pakistan', 'joule', 'imagery', 'mummify', 'notary', 'waterfall', 'kilowatt', 'instrument', 'plague', 'perjure', 'waterhole', 'linear', 'journal', 'pyramid', 'protocol', 'weir', 'malfunction', 'legato', 'warrior', 'warfare', 'whirlpool', 'polarity', 'leotard', 'welfare', 'wilderness', 'pressure', 'medley', 'Whitlam', 'Yellowstone', 'webinar', 'melody', 'witness', 'widget', 'Sinatra', 'Thiele', 'Vivaldi', 'vowel', 'whistle'];

export const lg4 = ['abrasion', 'caterpillar', 'impervious', 'precursor', 'shuttlecock', 'absorbent', 'cathedral', 'incognito', 'predicament', 'skirmish', 'acceptance', 'cessation', 'intuition', 'prescription', 'solicitor', 'accomplice', 'clandestine', 'irritable', 'presumably', 'spaghetti', 'acerbic', 'coagulate', 'lacklustre', 'procure', 'squadron', 'acknowledge', 'combination', 'larrikin', 'propensity', 'stubborn', 'admittance', 'concussion', 'linguine', 'prosperity', 'suburbia', 'admonish', 'confiscate', 'logistics', 'quiche', 'superior', 'alpaca', 'conundrum', 'macaw', 'ravenous', 'superstition', 'apologetic', 'convenient', 'marvellous', 'refurbish', 'surplus', 'appalled', 'corroboree', 'masonry', 'regimen', 'sustenance', 'apprehend', 'corrugated', 'masseur', 'rejuvenate', 'syndrome', 'armadillo', 'damask', 'matriarch', 'reliable', 'tahini', 'artificial', 'decadence', 'metropolitan', 'remembrance', 'tarantula', 'askance', 'decrepit', 'mirage', 'renegade', 'territorial', 'assessor', 'deodorant', 'modicum', 'repulsive', 'tinea', 'assistant', 'deteriorate', 'niche', 'resilient', 'traitor', 'attraction', 'diabolical', 'notorious', 'resplendent', 'triage', 'audacity', 'diadem', 'nullify', 'retinue', 'twelfth', 'barbarian', 'discipline', 'oblivious', 'reverberate', 'tyrant', 'barnacle', 'discussion', 'orthodontics', 'ridiculous', 'unanimous', 'barramundi', 'disinfectant', 'ostracise', 'salamander', 'university', 'bazaar', 'edifice', 'oxygen', 'sanitary', 'vacancy', 'begonia', 'embarrass', 'paralegal', 'scenario', 'vanquish', 'beneficial', 'espouse', 'parameter', 'schematic', 'vegetarian', 'bountiful', 'etiquette', 'philosopher', 'scholastic', 'volunteer', 'boutique', 'exceptional', 'pleasurable', 'scoundrel', 'wasabi', 'buttress', 'forage', 'porcupine', 'serendipity', 'wheatgerm', 'calibre', 'gullible', 'porpoise', 'serviceable'];

export const lsc4 = ['allegro', 'Alexander', 'abolition', 'Argentina', 'accelerate', 'collage', 'ancestry', 'acquit', 'Bhutan', 'astronomy', 'composition', 'centaur', 'alliance', 'constellation', 'barometer', 'conductor', 'citadel', 'arbitrate', 'hemisphere', 'conductivity', 'critique', 'dynasty', 'constituent', 'Kalahari', 'cyberspace', 'dialogue', 'excavation', 'independence', 'Malaysia', 'diameter', 'enamel', 'Medusa', 'manufacture', 'monolith', 'diffusion', 'exhibition', 'microlith', 'metropolis', 'Myanmar', 'electricity', 'extravaganza', 'Neolithic', 'multicultural', 'oasis', 'inertia', 'figurative', 'Olympia', 'parliament', 'Quebec', 'plutonium', 'glossary', 'pharaoh', 'pedestrian', 'sierra', 'potassium', 'harpsichord', 'prehistoric', 'professor', 'solstice', 'probability', 'instalment', 'primitive', 'prosecution', 'steppe', 'programming', 'maraca', 'sistrum', 'referendum', 'Switzerland', 'satellite', 'melodious', 'Socrates', 'refugee', 'tombolo', 'teleportation', 'monochrome', 'Sphinx', 'seniority', 'troposphere', 'theorem', 'montage', 'stegosaurus', 'transportation', 'tsunami', 'thermometer', 'panorama', 'Tunisia', 'ultraviolet', 'piccolo', 'recital', 'saxophone', 'semibreve', 'technique', 'theatre'];

export const lg5 = ['acclimatise', 'brigadier', 'delirium', 'knowledgeable', 'regrettable', 'affirmative', 'cantilever', 'diagnosis', 'notoriety', 'rescind', 'aikido', 'cartilage', 'diplodocus', 'peripheral', 'rhetorical', 'alacrity', 'cellophane', 'discrepancy', 'pheasant', 'sequester', 'altruism', 'cologne', 'diversification', 'physician', 'souvlaki', 'ambrosia', 'committal', 'enthusiasm', 'placebo', 'successor', 'architecture', 'communicable', 'eventually', 'pneumonia', 'sudoku', 'assassin', 'concoction', 'exacerbate', 'poultice', 'sycamore', 'assignment', 'creche', 'exaggerate', 'preferential', 'venomous', 'atrocious', 'dahlia', 'gerbera', 'prejudice', 'vivacious', 'augment', 'debacle', 'intelligible', 'quadriceps'];

export const lsc5 = ['cinematography', 'Acropolis', 'coalition', 'Afghanistan', 'cylindrical', 'contralto', 'cockatrice', 'cosmopolitan', 'bombora', 'Galileo', 'decrescendo', 'Confucius', 'discrimination', 'circumnavigate', 'hyperbola', 'expressionism', 'Egyptology', 'guarantor', 'crevasse', 'laboratory', 'flautist', 'Excalibur', 'inaugural', 'Gallipoli', 'parabola', 'glockenspiel', 'fiefdom', 'jurisdiction', 'meteorology', 'quadrilateral', 'haiku', 'Hercules', 'recession', 'Nullarbor', 'rhomboid', 'improvisation', 'megafauna', 'revolution', 'Pyrenees', 'statistician', 'karaoke', 'phoenix', 'superannuation', 'stalagmite', 'temperature', 'madrigal', 'primordial', 'symposium', 'Vesuvius', 'velocity', 'matinee', 'Michelangelo', 'mosaic', 'orchestra', 'rhapsody'];

export const combinedAll = [...lg1, ...lsc1, ...lg2, ...lsc2, ...lg3, ...lsc3, ...lg4, ...lsc4, ...lg5, ...lsc5];
export const last = ['matinee', 'Michelangelo'];

export const randWords = (itemsFromArray) => {
  const arrlg1 = random(lg1, itemsFromArray);
  const arrlsc1 = random(lsc1, itemsFromArray);
  const arrlg2 = random(lg2, itemsFromArray);
  const arrlsc2 = random(lsc2, itemsFromArray);
  const arrlg3 = random(lg3, itemsFromArray);
  const arrlsc3 = random(lsc3, itemsFromArray);
  const arrlg4 = random(lg4, itemsFromArray);
  const arrlsc4 = random(lsc4, itemsFromArray);
  const arrlg5 = random(lg5, itemsFromArray);
  const arrlsc5 = random(lsc5, itemsFromArray);

  return [...arrlg1, ...arrlsc1, ...arrlg2, ...arrlsc2, ...arrlg3, ...arrlsc3, ...arrlg4, ...arrlsc4, ...arrlg5, ...arrlsc5];
};
